//! SM-2, as the original course computes it — bit for bit, so a grade
//! given here schedules the same day the Python reference would.
//!
//! ```text
//! if quality >= 3:
//!     if reps == 0:   interval = 1
//!     elif reps == 1: interval = 6
//!     else:           interval = ceil(interval * ef)   # the OLD ef
//!     reps += 1
//! else:
//!     reps = 0; interval = 1
//! ef = max(1.3, ef + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02)))
//! ```

/// The three variables the algorithm keeps per item.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct State {
    pub ease: f64,
    pub interval: i64,
    pub reps: i64,
}

impl Default for State {
    fn default() -> Self {
        State { ease: 2.5, interval: 1, reps: 0 }
    }
}

pub const MIN_EASE: f64 = 1.3;

/// Seconds in a day: what an interval is multiplied by.
pub const DAY: f64 = 86_400.0;

/// One review of `quality` (0…5).
#[must_use]
pub fn step(s: State, quality: i64) -> State {
    let q = quality.clamp(0, 5);
    let (interval, reps) = if q >= 3 {
        let interval = match s.reps {
            0 => 1,
            1 => 6,
            _ => (s.interval as f64 * s.ease).ceil() as i64,
        };
        (interval, s.reps + 1)
    } else {
        (1, 0)
    };
    let miss = (5 - q) as f64;
    let ease = (s.ease + (0.1 - miss * (0.08 + miss * 0.02))).max(MIN_EASE);
    State { ease: (ease * 100.0).round() / 100.0, interval, reps }
}

/// The start of the day `t` falls in.
#[must_use]
pub fn day_start(t: f64) -> f64 {
    (t / DAY).floor() * DAY
}

/// When an item reviewed at `now` with this state comes due.
#[must_use]
pub fn due_after(now: f64, s: State) -> f64 {
    day_start(now) + s.interval as f64 * DAY
}

/// Whole days from `from`'s day to `to`'s day; negative when `to` is earlier.
#[must_use]
pub fn days_between(from: f64, to: f64) -> i64 {
    ((day_start(to) - day_start(from)) / DAY).round() as i64
}

/// The mastery stamp after a grade: up a step on a pass, down on a miss.
#[must_use]
pub fn mastery_after(mastery: i64, quality: i64) -> i64 {
    if quality >= 3 { (mastery + 1).min(5) } else { (mastery - 1).max(0) }
}

/// Where a run of grades leaves an item: the algorithm's three variables,
/// the day it comes due, when it was last graded, and the mastery stamp.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Replay {
    pub state: State,
    pub due: f64,
    pub reviewed: Option<f64>,
    pub mastery: i64,
}

/// Replays every grade an item was ever given, oldest first, as
/// `(when, quality)`. Each one is a [`step`] from what the one before it
/// left, so a device that holds the same grades shows the same schedule
/// however they reached it — which is why the grades replicate and the
/// schedule does not.
///
/// No grades is a fresh item: the default state, due at the epoch, never
/// reviewed. A caller with an item to write reads that as *nothing to
/// say* and leaves the row alone.
#[must_use]
pub fn replay(reviews: &[(f64, i64)]) -> Replay {
    let mut r = Replay { state: State::default(), due: 0.0, reviewed: None, mastery: 0 };
    for (at, quality) in reviews {
        r.state = step(r.state, *quality);
        r.due = due_after(*at, r.state);
        r.reviewed = Some(*at);
        r.mastery = mastery_after(r.mastery, *quality);
    }
    r
}

/// The words the grade pad wears.
pub const WORDS: [&str; 6] = ["blank", "wrong", "almost", "hard", "good", "easy"];

#[cfg(test)]
mod tests {
    use super::*;

    /// Cases from the original's `tests/fixtures/sm2-parity.json`, which
    /// were generated by the Python reference.
    #[test]
    fn parity_with_the_python_reference() {
        let fresh = State::default();
        for (q, ease, interval, reps) in [
            (5, 2.6, 1, 1),
            (4, 2.5, 1, 1),
            (3, 2.36, 1, 1),
            (2, 2.18, 1, 0),
            (1, 1.96, 1, 0),
            (0, 1.7, 1, 0),
        ] {
            assert_eq!(step(fresh, q), State { ease, interval, reps }, "fresh q{q}");
        }
        let second = State { ease: 2.5, interval: 1, reps: 1 };
        assert_eq!(step(second, 5), State { ease: 2.6, interval: 6, reps: 2 });
        assert_eq!(step(second, 4), State { ease: 2.5, interval: 6, reps: 2 });
        // The third pass multiplies by the ease *before* it moves.
        let third = State { ease: 2.5, interval: 6, reps: 2 };
        assert_eq!(step(third, 5), State { ease: 2.6, interval: 15, reps: 3 });
        assert_eq!(step(third, 3), State { ease: 2.36, interval: 15, reps: 3 });
        // A miss resets, and the ease never goes under 1.3.
        let worn = State { ease: 1.35, interval: 30, reps: 7 };
        assert_eq!(step(worn, 0), State { ease: 1.3, interval: 1, reps: 0 });
    }

    /// A replay is the steps, taken one after another: the same state a
    /// caller would reach by stepping each grade in turn, with the due day
    /// of the last one.
    #[test]
    fn a_replay_is_what_stepping_the_grades_one_by_one_leaves() {
        let day = |n: i64| kernel::time::ts(2026, 9, 1, 19, 0) + n as f64 * DAY;
        let grades = [5, 4, 2, 3, 5, 5];
        let (mut state, mut mastery) = (State::default(), 0);
        for (n, q) in grades.iter().enumerate() {
            let run: Vec<(f64, i64)> =
                grades.iter().take(n + 1).enumerate().map(|(i, q)| (day(i as i64), *q)).collect();
            state = step(state, *q);
            mastery = mastery_after(mastery, *q);
            let replayed = replay(&run);
            assert_eq!(replayed.state, state, "after {} grades", n + 1);
            assert_eq!(replayed.mastery, mastery);
            assert_eq!(replayed.reviewed, Some(day(n as i64)));
            assert_eq!(replayed.due, due_after(day(n as i64), state));
        }
        // No grades is a fresh item and says nothing about a day.
        let fresh = replay(&[]);
        assert_eq!(fresh.state, State::default());
        assert_eq!((fresh.due, fresh.reviewed, fresh.mastery), (0.0, None, 0));
    }

    #[test]
    fn days_and_due_dates() {
        let noon = kernel::time::ts(2026, 9, 1, 12, 0);
        assert_eq!(day_start(noon), kernel::time::ts(2026, 9, 1, 0, 0));
        let s = State { ease: 2.5, interval: 6, reps: 2 };
        assert_eq!(due_after(noon, s), kernel::time::ts(2026, 9, 7, 0, 0));
        assert_eq!(days_between(noon, kernel::time::ts(2026, 9, 7, 3, 0)), 6);
        assert_eq!(days_between(noon, kernel::time::ts(2026, 8, 30, 23, 0)), -2);
        assert_eq!(mastery_after(4, 5), 5);
        assert_eq!(mastery_after(5, 5), 5);
        assert_eq!(mastery_after(0, 1), 0);
        assert_eq!(mastery_after(3, 2), 2);
    }
}
